"""Build the team-game warehouse fact table from per-team CSV extracts.

Input:
    to_games_csvs/*.csv

Output:
    warehouse/fact_team_game.csv

Each source CSV contains one team's historical game log. Concatenating them
creates a long fact table with one row per team per game, which is the source for
team profiles, standings, and the team-level prediction dataset.
"""

import glob

import pandas as pd


# Collect every team export generated by `games/all_games.py` or refreshed by
# `update_games_2526.py`.
files = glob.glob("to_games_csvs/*.csv")

# Stack all team CSVs into one normalized fact table.
warehouse_df = pd.concat(
    [pd.read_csv(f) for f in files],
    ignore_index=True
)

# Convert dates before sorting so downstream rolling features and time splits are
# based on actual chronological order instead of string order.
warehouse_df["GAME_DATE"] = pd.to_datetime(warehouse_df["GAME_DATE"])
warehouse_df = warehouse_df.sort_values("GAME_DATE")

warehouse_df.to_csv("warehouse/fact_team_game.csv", index=False)
