 SELECT p.season_id,
    p.player_id_raw,
    p.game_id,
    p.game_date,
    p.matchup,
    p.wl,
    p.min,
    p.fgm,
    p.fga,
    p.fg_pct,
    p.fg3m,
    p.fg3a,
    p.fg3_pct,
    p.ftm,
    p.fta,
    p.ft_pct,
    p.oreb,
    p.dreb,
    p.reb,
    p.ast,
    p.stl,
    p.blk,
    p.tov,
    p.pf,
    p.pts,
    p.plus_minus,
    p.video_available,
    p.season,
    p.player_id,
    p.player_name
   FROM fact_player_game p
     JOIN dim_allstar_cohort c ON c.player_name = p.player_name;
     